### PR TITLE
Game update

### PR DESCRIPTION
**Pull request by Lymkwi**
It's finally time to update the default mods so that we can have more items/nodes to put into quests.
Because it is the first update of this repository, I created my [branch](https://github.com/LeMagnesium/minetest_game/tree/minetestforfun_skyblock), merged from Minetest Game, and I now ask you to approve the code I merged between master and that branch.

### CODE REVIEW

**Comment by BetterToAutomateTheWorld** [comment]
I agreed with this PR, it seems to be ok for me, need a second check from @crabman77.

Can you list the new nodes/items ?

**Comment by ObaniGemini** [comment]
The biggest part of this update is about mapgen and fire. Shouldn't we remove both ?

**Comment by BetterToAutomateTheWorld** [comment]
@ObaniGemini No. This is not the purpose of a merge of the game...

**Comment by Lymkwi** [comment]
@ObaniGemini I didn't remove the mapgen because A° it's deactivated by skyblock and B° it makes less collisions possible when running `git rebase`. Also, the fire is disabled so, yes, that update is mostly useless for those, even though it makes merging the next updates easier for me. The most important point here is the addition of a few nodes, including the mushrooms and their spores.
EDIT: I updated to enable the mossycobble ABM turning cobble into mossy after a long interval next to water nodes.

**Comment by BetterToAutomateTheWorld** [comment]
Up, @crabman77 again for a second check

**Comment by ghost** [comment]
ok for me.

**Comment by Lymkwi** [comment]
Merged.
https://github.com/MinetestForFun/server-minetestforfun-skyblock/commit/d0f25a9e96ddc4838a2d1767e20c46d08430ae51

**Pull request closed without merging**
